# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergyType', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr', models.CharField(max_length=2)),
                ('rh_f', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('blood_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthband.BloodType')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_public', models.BooleanField(default=False)),
                ('condition_private', models.BooleanField(default=False)),
                ('blood_type_public', models.BooleanField(default=False)),
                ('blood_type_private', models.BooleanField(default=False)),
                ('allergy_public', models.BooleanField(default=False)),
                ('allergy_private', models.BooleanField(default=False)),
                ('meds_public', models.BooleanField(default=False)),
                ('meds_private', models.BooleanField(default=False)),
                ('observation_public', models.BooleanField(default=False)),
                ('observation_private', models.BooleanField(default=False)),
                ('encounter_public', models.BooleanField(default=False)),
                ('encounter_private', models.BooleanField(default=False)),
                ('med_dispense_public', models.BooleanField(default=False)),
                ('med_dispense_private', models.BooleanField(default=False)),
                ('med_order_public', models.BooleanField(default=False)),
                ('med_order_private', models.BooleanField(default=False)),
                ('operation_def_public', models.BooleanField(default=False)),
                ('operation_def_private', models.BooleanField(default=False)),
                ('procedure_public', models.BooleanField(default=False)),
                ('procedure_private', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthband.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='allergy',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthband.Patient'),
        ),
    ]
