# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthband', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
