# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-19 00:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthband', '0003_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='address_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='address_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='dob_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='dob_public',
            field=models.BooleanField(default=False),
        ),
    ]
