# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160302004832 on 2016-04-25 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthband', '0005_auto_20160424_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='hospitalZip',
            field=models.CharField(default='', max_length=2),
        ),
    ]
