# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160302004832 on 2016-05-01 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthband', '0010_remove_provider_hcontactphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='hContactPhone',
            field=models.CharField(default='', max_length=15, verbose_name='Phone Number'),
        ),
    ]
