# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160302004832 on 2016-05-01 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthband', '0014_auto_20160430_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='hContactEmail',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='hContactFName',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='hContactLName',
        ),
    ]
